config/routes.rb
AdsProject::Application.routes.draw do

  devise_for :users, path_prefix: 'my'

  resources :users
  resources :ads
  resources :categories, except: :show

  get '/ads/:id/verify', to: 'ads#verify', as: 'verify'
  get '/ads/:id/approve', to: 'ads#approve', as: 'approve'
  get '/ads/:id/reject', to: 'ads#reject', as: 'reject'

  get '/verified_ads', to: 'pages#verified_ads'

  root to: 'ads#index'

end

app/models/ad.rb
# == Schema Information
#
# Table name: ads
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  state       :string(255)
#

class Ad < ActiveRecord::Base
  attr_accessible :description, :title, :images_attributes, :category_ids
  belongs_to :user
  has_many :images, dependent: :destroy, autosave: :true
  has_many :categorizations, dependent: :destroy, autosave: :true
  has_many :categories, through: :categorizations
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :title, presence: true,
                    length: { maximum: 80 }

  validates :description, presence: true,
                          length: { maximum: 500 }

  validates :user_id, presence: true

  default_scope order: 'ads.updated_at DESC'

  scope :published, -> { where(state: 'published') }
  scope :verified,  -> { where(state: 'verified') }

  before_save do |ad|
    ad.state = 'draft' if ad.title_changed? || ad.description_changed?
  end

  state_machine :state, initial: :draft do

    event :verify do
      transition draft: :verified
    end

    event :approve do
      transition verified: :approved
    end

    event :reject do
      transition verified: :rejected
    end

    event :publish do
      transition approved: :published
    end

    event :archive do
      transition published: :archived
    end

    event :refresh do
      transition all - [:draft] => :draft
    end
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  load_and_authorize_resource
  respond_to :html

  def index
    @ads = @ads.published.paginate(page: params[:page],
                                   per_page: 5,
                                   include: [:images, :categories] )
  end

  def create
    @ad = current_user.ads.build(params[:ad])
    flash[:success] = 'Ad created!' if @ad.save
    respond_with @ad
  end

  def new
    @ad.images.build
  end

  def update
    flash[:success] = 'Ad updated!' if @ad.update_attributes(params[:ad])
    respond_with @ad
  end

  def destroy
    @ad.destroy
    redirect_to current_user, notice: 'Successfuly destroyed ad!'
  end

  def verify
    @ad.verify
    render 'show'
  end

  def approve
    @ad.approve
    render 'show'
  end

  def reject
    @ad.reject
    render 'show'
  end
end

app/views/ads/_ad.html.erb
      <div class="row" id="ad">
        <div class="span2">
        <% if ad.images.any? %>
          <% img = ad.images.first %>
          <%= image_tag(img.image_url, class: 'center') %>
        <% end %>
        </div>
        <div class="span10">
          <h2><%= link_to ad.title, ad_path(ad) %></h2>
          <p> Categories:
          <% ad.categories.each do |category| %>
            <span class="label label-info"><%= category.category_name %></span>
          <% end %>
          </p>
          <p><%= ad.description %></p>
          <p><span class="label"><%= ad.state %></span> Updated <%= time_ago_in_words(ad.updated_at) %> ago</p>
          <% if can? :update, ad %>
          <%= link_to "edit", edit_ad_path(ad), class: 'btn btn-mini btn-primary'  %>
          <% end %>
          <% if can? :destroy, ad %>
          <%= link_to "delete", ad, method: :delete, data: { confirm: "You sure want to delete ad?" }, title: ad.title, class: "btn btn-mini btn-danger" %>
          <% end %>
        </div>
      </div>

app/views/ads/_form.html.erb
<% provide(:title, controller.action_name.humanize + " ad") %>
      <div class="row">
        <div class="span6 offset3">
          <h1><%= controller.action_name.humanize + " ad" %></h1>
          <%= simple_nested_form_for @ad do |f| %>
            <fieldset>
              <%= f.input :title, required: false, autofocus: true, input_html: { class: "span6" } %>
              <%= f.input :description, required: false, input_html: { class: "span6", rows: 5 }  %>
              <%= f.collection_check_boxes :category_ids, Category.all, :id, :category_name %>

              <%= f.simple_fields_for :images do |i| %>
                <%= i.input :image_url, required: false, input_html: { class: "span6" } %>
                <p><%= i.link_to_remove "Remove image", class: "btn btn-mini btn-danger" %></p>
              <% end %>
              <p><%= f.link_to_add "Add image", :images, class: "btn btn-mini btn-primary" %></p>

              <%= f.button :submit, "Save", class: "btn-primary" %>
              <%= link_to "Cancel", current_user, class: "btn" %>
            </fieldset>
          <% end %>
        </div>
      </div>

app/views/ads/index.html.erb
<% provide(:title, 'Home') %>
      <% if !user_signed_in? %>
      <div class="row">
        <div class="span12">
          <div class="center hero-unit">
            <h1>Welcome to the ADS project</h1>
            <h2>sign up if you don't have an account</h2>
            <%= link_to "Sign up", new_user_registration_path , class: "btn btn-large btn-primary" %>
          </div>
        </div>
      </div>
      <% end %>

      <% @ads.each do |ad| %>
<%= render ad %>
      <% end %>
      <%= will_paginate @ads %>

app/views/ads/show.html.erb
<% provide(:title, @ad.title) %>
      <div class="row">
        <div class="span12">
          <h1><%= @ad.title %></h1>
          <p> Categories:
          <% @ad.categories.each do |category| %>
            <span class="label label-info"><%= category.category_name %></span>
          <% end %>
          </p>
          <div id="images">
          <% @ad.images.each do |img| %>
            <%= image_tag(img.image_url, class: 'center') %>
          <% end %>
          </div>
          <p><%= @ad.description %></p>
          <p><span class="label"><%= @ad.state %></span> Created by
        <% if can? :read, @users %>
          <%= link_to @ad.user.name, user_path(@ad.user) %> <%= time_ago_in_words(@ad.created_at) %>
        <% else %>
          <%= @ad.user.name %> <%= time_ago_in_words(@ad.created_at) %>
        <% end %>
          ago. Updated <%= time_ago_in_words(@ad.updated_at) %> ago.
          </p>
        <% if (@ad.state == 'draft') && (can? :verify, @ad) %>
          <%= link_to "verify", verify_path(@ad), class: 'btn btn-success'  %>
        <% end %>
        <% if (@ad.state == 'verified') && (can? :approve, @ad) %>
          <%= link_to "approve", approve_path, class: 'btn btn-success'  %>
          <%= link_to "reject", reject_path, class: 'btn btn-warning' %>
        <% end %>
        <% if can? :update, @ad %>
          <%= link_to "edit", edit_ad_path(@ad), class: "btn btn-primary"  %>
        <% end %>
        <% if can? :destroy, @ad %>
          <%= link_to "delete", @ad, method: :delete, data: { confirm: "You sure want to delete ad?" }, class: "btn btn-danger" %>
        <% end %>
        </div>
      </div>