config/routes.rb
AdsProject::Application.routes.draw do

  devise_for :users, path_prefix: 'my'

  resources :users
  resources :ads
  resources :categories, except: :show

  get '/ads/:id/verify', to: 'ads#verify', as: 'verify'
  get '/ads/:id/approve', to: 'ads#approve', as: 'approve'
  get '/ads/:id/reject', to: 'ads#reject', as: 'reject'

  get '/verified_ads', to: 'pages#verified_ads'

  root to: 'ads#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string(255)
#  role                   :string(255)
#

class User < ActiveRecord::Base
  include Enumerize
  before_create :set_role

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation,
                  :remember_me, :name
  # attr_accessible :title, :body

  has_many :ads, dependent: :destroy

  validates :name, presence: true, length: { maximum: 80 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }

  enumerize :role, in: %w(user admin), predicates: true

  private

  def set_role
    self.role ||= "user"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  respond_to :html

  def index
    @users = @users.paginate(page: params[:page])
    authorize! :update, User
  end

  def show
    @ads = @user.ads.paginate(page: params[:page],
                              per_page: 5,
                              include: [:images, :categories])
  end

  def create
    @user.role = params[:user][:role] if can? :assign_role, @user
    flash[:success] = 'User created!' if @user.save
    respond_with @user
  end

  def update
    @user.role = params[:user][:role] if can? :assign_role, @user
    flash[:success] = 'User updated!' if @user.save
    respond_with @user
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: 'User destroyed!'
  end
end

app/views/users/_user.html.erb
            <tr>
              <td>
                <p>
                  <%= link_to user.name, user %>
                  <span class="label label-<%= (user.role == 'admin') ? 'important' : 'success' %>"><%= user.role %></span>
                </p>
              </td>
              <td>
                <p class="right">
                <% if (can? :destroy, User) && (user != current_user) %>
                  <%= link_to "Delete", user, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-mini btn-danger' %>
                  <%= link_to "Change role", edit_user_path(user), class: 'btn btn-mini btn-primary'  %>
                <% end %>
                </p>
              </td>
            </tr>

app/views/users/_user_info.html.erb
          <h3 class="center">Account details</h3>
          <table class="table table-striped table-bordered">
            <tr>
              <th>name:</th><td><%= @user.name %></td>
            </tr>
            <tr>
              <th>id:</th><td><%= @user.id %></td>
            </tr>
            <tr>
              <th>email:</th><td><%= @user.email %></td>
            </tr>
            <tr>
              <th>role:</th><td><%= @user.role %></td>
            </tr>
            <tr>
              <th>ads count:</th><td><%= @ads.count %></td>
            </tr>
          </table>

app/views/users/edit.html.erb
<% provide(:title, 'Change user role') %>
      <div class="row">
      <h1>Change user role</h1>

        <div class="span6 offset3">
          <h3 class="center">Account details</h3>

          <table class="table table-striped table-bordered">
            <tr>
              <th>name:</th><td><%= @user.name %></td>
            </tr>
            <tr>
              <th>id:</th><td><%= @user.id %></td>
            </tr>
            <tr>
              <th>email:</th><td><%= @user.email %></td>
            </tr>
            <tr>
              <th>Sign up date:</th><td><%= @user.created_at %></td>
            </tr>
          </table>

          <%= simple_form_for @user do |f| %>
            <%= f.input :role, as: :radio_buttons, required: false, input_html: { class: 'span6' } %>

            <%= f.button :submit, class: 'btn-primary' %>
            <%= link_to 'Cancel', users_path, class: 'btn' %>
          <% end %>
        </div>
      </div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
      <h1>All users</h1>
      <div class="row">
        <div class="span6 offset3">
          <% if can? :create, User %>
          <p class="center">
            <%= link_to "Create user", new_user_path, class: "btn btn-primary" %>
          </p>
          <% end %>
          <table class="table table-striped">
          <% @users.each do |user| %>
<%= render user %>
          <% end %>
          </table>
          <%= will_paginate %>
        </div>
      </div>

app/views/users/new.html.erb
<% provide(:title, 'Create new user') %>
      <div class="row">
      <h1>Create new user</h1>

        <div class="span6 offset3">
          <%= simple_form_for @user do |f| %>

          <%= f.input :name, required: false, autofocus: true, input_html: { class: 'span6' } %>
          <%= f.input :email, required: false, autofocus: true, input_html: { class: 'span6' } %>
          <%= f.input :password, required: false, input_html: { class: 'span6' } %>
          <%= f.input :password_confirmation, required: false, input_html: { class: 'span6' } %>
          <%= f.input :role, as: :radio_buttons, required: false, input_html: { class: 'span6' } %>

          <%= f.button :submit, "Sign up", class: 'btn-primary' %>
          <%= link_to 'Cancel', users_path, class: 'btn' %>
        <% end %>
        </div>
      </div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
      <h1 class="header"><%= @user.name %></h1>
      <div class="row">
        <div class="span8 offset2">
<%= render partial: 'user_info' %>
        <% if can? :create, Ad %>
          <%= link_to "Create new ad!", new_ad_path, class: "btn btn-large btn-primary" %>
        <% end %>
        </div>
      </div>

<% if @ads.any? %>
      <h2 class="center">List of ads</h2>
      <% @ads.each do |ad| %>
<%= render ad %>
      <% end %>
      <%= will_paginate @ads %>
<% end %>