config/routes.rb
AdsProject::Application.routes.draw do

  devise_for :users, path_prefix: 'my'

  resources :users
  resources :ads
  resources :categories, except: :show

  get '/ads/:id/verify', to: 'ads#verify', as: 'verify'
  get '/ads/:id/approve', to: 'ads#approve', as: 'approve'
  get '/ads/:id/reject', to: 'ads#reject', as: 'reject'

  get '/verified_ads', to: 'pages#verified_ads'

  root to: 'ads#index'

end

app/views/layouts/_debug.html.erb
<% if Rails.env.development? %>
      <div id="debug">
        <%= debug(params) %>
      </div>
<% end %>

app/views/layouts/_flash_notice.html.erb
<% flash.each do |type, message| %>
      <div class="alert <%= alert_type(type) %>">
        <a class="close" data-dismiss="alert">×</a>
        <%= message %>
      </div>
<% end %>

app/views/layouts/_navbar.html.erb
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "ADS project", root_path, class: "brand" %>
          <nav>
            <ul class="nav pull-right">
            <% if user_signed_in? %>
              <% if current_user.admin? %>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Categories", categories_path %></li>
              <li><%= link_to "Verified ads", verified_ads_path %></li>
              <% end %>
              <% if current_user.user? %>
              <li><%= link_to "Create ad", new_ad_path %></li>
              <% end %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "My account", current_user %></li>
                  <li><%= link_to "Settings", edit_user_registration_path  %></li>
                  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ADS project | <%= yield(:title) %></title>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
  </head>
  <body>
<%= render 'layouts/navbar' %>
    <div class="container">
<%= render 'layouts/flash_notice' %>
<%= yield %>
      <footer class="footer">
        <p class="pull-right"><%= link_to "Back to top", "#" %></p>
        <p><%= link_to "ADS project", root_path %></p>
<%= render 'layouts/debug' %>
      </footer>
    </div>
  </body>
</html>